### ISSUE TITLE
NullPointerException OTWrapper$4.onError

### ISSUE THREAD

**Issue by H-Sayed** [opentok/accelerator-sample-apps-android#8]
### **General information**

- Library version(s): com.opentok.android:opentok-accelerator-core:1.0.17
- iOS/Android/Browser version(s): Android Lollipop , Nougat , Marshmallow , Oreo
- Devices/Simulators/Machine affected: Samsung View , Note 4 , Nexus 6p
- Reproducible in the demo project? (Yes/No):  No

#### Expected behavior
SDK should recover if an internal error happened and should check for null values before making comparisons 

#### Actual behavior
Sdk crash internally 

#### Crash log? Screenshots? Videos? Sample project?
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'com.opentok.android.Stream$StreamVideoType com.opentok.android.Stream.getStreamVideoType()' on a null object reference

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.opentok.android.Stream$StreamVideoType com.opentok.android.Stream.getStreamVideoType()' on a null object reference
       at com.tokbox.android.otsdkwrapper.wrapper.OTWrapper$4.onError(OTWrapper.java:1307)
       at com.opentok.android.PublisherKit.onError(PublisherKit.java:939)
       at com.opentok.android.PublisherKit$4.run(PublisherKit.java:923)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5643)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by marinaserranomontes** [comment]
Hi @H-Sayed ,

Yes, if the stream doesn't exist, it will crash, but we should catch this case in the accelerator-core-android. We will add a fix shortly.

Thanks for the bug report.

Best,
Marina

**Comment by marinaserranomontes** [comment]
Hi @H-Sayed ,

A new version of the accelerator-core has been published with the fix (v1.0.20)
https://github.com/opentok/accelerator-sample-apps-android/blob/master/AcceleratorSampleApp/app/build.gradle#L37

Best,
Marina
